server:
  port: 8081
spring:
  application:
    name: usermanagement
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
